const sampleData = {
  id: 0,
  audioUrl:
    "https://res.cloudinary.com/dqssqzt3y/video/upload/v1729571976/The_Race_Audio_rktzao.mp3",
  metaData: {
    duration: 89.5035,
    lesson: {
      slug: "the-race-audio",
      title: "The Race Audio",
    },
    lessonSet: { slug: "the-race-lesson-set", name: "The Race Lesson Set" },
    course: { slug: "original-english", name: "Original English" },
  },
  lyrics: [
    {
      id: 0,
      text: "A red Ferrari pulls up next to him.",
      ipa: "ə rɛd fəˈrɑri pʊlz ʌp nɛkst tə hɪm",
      translation: "Một chiếc Ferrari màu đỏ chạy đến và dừng cạnh anh ấy.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 13.882487,
      endTime: 17.049515,
    },
    {
      text: "Allen and Tom take off!",
      ipa: "ˈælən ænd tɑm teɪk ɔf",
      translation: "Allen và Tom lao đi!",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 62.831067,
      endTime: 64.891444,
      id: 1,
    },
    {
      text: "Allen and Tom wait at the light.",
      ipa: "ˈælən ænd tɑm weɪt æt ðə laɪt",
      translation: "Allen và Tom chờ ở đèn đỏ.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 53.155763,
      endTime: 57.04807,
      id: 2,
    },
    {
      text: "Allen is the winner!",
      ipa: "ˈælən ɪz ðə ˈwɪnər",
      translation: "Allen là người chiến thắng!",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 86.507881,
      endTime: 88.978238,
      id: 3,
    },
    {
      text: "Allen looks at him",
      ipa: "ˈælən lʊks æt hɪm",
      translation: "Allen nhìn anh ta.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 22.502207,
      endTime: 25.304226,
      id: 4,
    },
    {
      text: 'Allen says, "All right, you\'re on!"',
      ipa: 'ˈælən sɛz, "ɔl raɪt, jʊr ɑn!"',
      translation: 'Allen nói, "Được thôi, chơi luôn!"',
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 37.220954,
      endTime: 41.687468,
      id: 5,
    },
    {
      text: 'Allen says, "You wish. I\'m gonna beat you and your sorry-ass car."',
      ipa: 'ˈælən sɛz, "ju wɪʃ. aɪm ˈɡʌnə bit ju ænd jʊr ˈsɑri-æs kɑr."',
      translation:
        'Allen nói, "Mơ đi. Tao sẽ đánh bại mày và cái xe tệ hại của mày."',
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 45.739963,
      endTime: 53.155763,
      id: 6,
    },
    {
      text: "Allen zooms past Tom, laughing.",
      ipa: "ˈælən zumz pæst tɑm, ˈlæfɪŋ",
      translation: "Allen phóng qua Tom, cười lớn.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 80.432223,
      endTime: 83.430733,
      id: 7,
    },
    {
      text: "and comes to a stop light.",
      ipa: "ænd kʌmz tə ə stɑp laɪt",
      translation: "và dừng lại ở đèn đỏ.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 11.521551,
      endTime: 13.882487,
      id: 8,
    },
    {
      text: "and realizes that the driver is Tom Cruise!",
      ipa: "ænd ˈriəˌlaɪzɪz ðæt ðə ˈdraɪvər ɪz tɑm kruz",
      translation: "và nhận ra rằng người lái xe là Tom Cruise!",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 25.304226,
      endTime: 29.550284,
      id: 9,
    },
    {
      text: "But suddenly, blue and red lights appear behind Tom.",
      ipa: "bʌt ˈsʌdənli, blu ænd rɛd laɪts əˈpɪr bɪˈhaɪnd tɑm",
      translation:
        "Nhưng đột nhiên, ánh sáng xanh và đỏ xuất hiện phía sau Tom.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 69.835605,
      endTime: 74.948589,
      id: 10,
    },
    {
      text: "He is riding down Van Ness street",
      ipa: "hi ɪz ˈraɪdɪŋ daʊn væn nɛs strit",
      translation: "Anh ấy đang chạy xe xuống đường Van Ness.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 8.913974,
      endTime: 11.521551,
      id: 11,
    },
    {
      text: "He looks over at Allen.",
      ipa: "hi lʊks ˈoʊvər æt ˈælən",
      translation: "Anh ta nhìn qua Allen.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 20.303184,
      endTime: 22.502207,
      id: 12,
    },
    {
      text: 'He says, "When the light turns green, let\'s race."',
      ipa: 'hi sɛz, "wɛn ðə laɪt tɜrnz ɡrin, lɛts reɪs."',
      translation: 'Anh ấy nói, "Khi đèn chuyển sang xanh, chúng ta đua nhé."',
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 32.267677,
      endTime: 37.220954,
      id: 13,
    },
    {
      text: 'He yells, "Better luck next time!"',
      ipa: 'hi jɛlz, "ˈbɛtər lʌk nɛkst taɪm!"',
      translation: 'Anh ấy hét lên, "Lần sau may mắn hơn nhé!"',
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 83.430733,
      endTime: 86.507881,
      id: 14,
    },
    {
      text: "It's five o'clock and Allen is riding his motorcycle in San Francisco.",
      ipa: "ɪts faɪv əˈklɑk ænd ˈælən ɪz ˈraɪdɪŋ hɪz ˈmoʊtərˌsaɪkəl ɪn ˌsæn frænˈsɪskoʊ.",
      translation:
        "Bây giờ là năm giờ và Allen đang chạy xe máy ở San Francisco.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 2.104309,
      endTime: 8.913974,
      id: 15,
    },
    {
      text: "It's the police.",
      ipa: "ɪts ðə pəˈlis",
      translation: "Đó là cảnh sát.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 74.948589,
      endTime: 78.921553,
      id: 16,
    },
    {
      text: "Suddenly, the light turns green.",
      ipa: "ˈsʌdənli, ðə laɪt tɜrnz ɡrin",
      translation: "Đột nhiên, đèn chuyển sang màu xanh.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 60.21084,
      endTime: 62.831067,
      id: 17,
    },
    {
      text: "The driver's wearing dark sun glasses.",
      ipa: "ðə ˈdraɪvərz ˈwɛrɪŋ dɑrk ˈsʌn ˌɡlæsəz",
      translation: "Người lái xe đang đeo kính râm tối màu.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 17.049515,
      endTime: 20.303184,
      id: 18,
    },
    {
      text: "The Race",
      ipa: "ðə reɪs",
      translation: "Cuộc đua",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 0,
      endTime: 2.104309,
      id: 19,
    },
    {
      text: "They pull him over.",
      ipa: "ðeɪ pʊl hɪm ˈoʊvər",
      translation: "Họ yêu cầu anh ấy dừng lại.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 78.921553,
      endTime: 80.432223,
      id: 20,
    },
    {
      text: "They rev their engines.",
      ipa: "ðeɪ rɛv ðɛr ˈɛnʤənz",
      translation: "Họ nổ máy xe của mình.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 57.04807,
      endTime: 60.21084,
      id: 21,
    },
    {
      text: "They zoom down Van Ness at top speed.",
      ipa: "ðeɪ zum daʊn væn nɛs æt tɑp spid",
      translation: "Họ phóng xuống đường Van Ness với tốc độ tối đa.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 64.891444,
      endTime: 68.277917,
      id: 22,
    },
    {
      text: "Tom is winning.",
      ipa: "tɑm ɪz ˈwɪnɪŋ",
      translation: "Tom đang dẫn đầu.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 68.277917,
      endTime: 69.835605,
      id: 23,
    },
    {
      text: 'Tom says, "I\'m gonna smoke you, sucka!"',
      ipa: 'tɑm sɛz, "aɪm ˈɡʌnə smoʊk ju, ˈsʌkə!"',
      translation: 'Tom nói, "Tao sẽ cho mày hít khói, thằng ngốc!"',
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 41.687468,
      endTime: 45.739963,
      id: 24,
    },
    {
      text: "Tom sneers at Allen.",
      ipa: "tɑm snɪrz æt ˈælən",
      translation: "Tom cười khẩy với Allen.",
      imgUrl: "no-imgUrl",
      altText: "no-altText",
      imgCredit: "no-credit",
      type: "narrative",
      startTime: 29.550284,
      endTime: 32.267677,
      id: 25,
    },
  ],
};

export { sampleData };
